/**
 * Data pipeline: extracted Last Epoch assets -> normalized data/game/game.json.
 *
 * Run with:  npm run data:parse
 *
 * STATUS: scaffold. The reader below is written against AssetRipper's typical
 * output shape (ScriptableObjects exported as YAML/JSON under an assets tree),
 * but the exact Last Epoch field names are UNVERIFIED from a dev machine without
 * the game files. Phase 2 is: you run extract.md locally, share a small sample of
 * the exported assets, and we correct the `map*` functions against the real shape.
 * Until then this parser exits with guidance if it finds no raw input.
 *
 * Contract: whatever this writes MUST validate against ../schema.ts (GameData).
 */
import fs from "node:fs";
import path from "node:path";
import { GameData } from "./schema";

const ROOT = process.cwd();
const RAW_DIR = process.env.LE_RAW_DIR || path.join(ROOT, "tools", "data-pipeline", "raw");
const OUT_DIR = path.join(ROOT, "data", "game");
const OUT_FILE = path.join(OUT_DIR, "game.json");

function hasRawInput(): boolean {
  return fs.existsSync(RAW_DIR) && fs.readdirSync(RAW_DIR).length > 0;
}

/**
 * ---- Category mappers (Phase 2: fill against real extracted assets) ----
 * Each takes the parsed raw asset collection and returns normalized records.
 * They currently return [] so the pipeline is runnable end-to-end; wire them up
 * once we've seen the real asset field names.
 */
function mapClasses(_raw: unknown): GameData["classes"] {
  return [];
}
function mapSkills(_raw: unknown): GameData["skills"] {
  return [];
}
function mapPassives(_raw: unknown): GameData["passives"] {
  return [];
}
function mapAffixes(_raw: unknown): GameData["affixes"] {
  return [];
}
function mapUniques(_raw: unknown): GameData["uniques"] {
  return [];
}
function mapAilments(_raw: unknown): GameData["ailments"] {
  return [];
}
function mapIdols(_raw: unknown): GameData["idols"] {
  return [];
}
function mapBlessings(_raw: unknown): GameData["blessings"] {
  return [];
}

/** Load the raw extracted assets. Shape TBD — refined once we see real output. */
function loadRaw(): unknown {
  // AssetRipper commonly emits many files; a future version walks RAW_DIR and
  // groups by MonoBehaviour script class. For now, return a placeholder handle.
  return { dir: RAW_DIR };
}

function main() {
  if (!hasRawInput()) {
    console.error(
      [
        "No extracted assets found in:",
        `  ${RAW_DIR}`,
        "",
        "Phase 2 steps (see tools/data-pipeline/extract.md):",
        "  1. Locate your Last Epoch install (Steam → right-click → Manage → Browse local files).",
        "  2. Extract game assets with AssetRipper into tools/data-pipeline/raw/",
        "  3. Re-run: npm run data:parse",
        "",
        "The app runs on data/sample/game.json until data/game/game.json exists.",
      ].join("\n"),
    );
    process.exit(1);
  }

  const raw = loadRaw();
  const data = GameData.parse({
    meta: { source: "extracted", gameVersion: "unknown", note: "Generated by tools/data-pipeline/parse.ts" },
    classes: mapClasses(raw),
    skills: mapSkills(raw),
    passives: mapPassives(raw),
    affixes: mapAffixes(raw),
    uniques: mapUniques(raw),
    ailments: mapAilments(raw),
    idols: mapIdols(raw),
    blessings: mapBlessings(raw),
  });

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT_FILE, JSON.stringify(data, null, 2));
  const counts = {
    classes: data.classes.length,
    skills: data.skills.length,
    passives: data.passives.length,
    affixes: data.affixes.length,
    uniques: data.uniques.length,
  };
  console.log(`Wrote ${OUT_FILE}`);
  console.log(JSON.stringify(counts, null, 2));
  if (Object.values(counts).every((n) => n === 0)) {
    console.warn("\nAll categories are empty — the map* functions are still stubs. Wire them up in Phase 2.");
  }
}

main();
